In [3]:
import pandas as pd
from statsbombpy import sb
from mplsoccer import Pitch, VerticalPitch, FontManager, Sbopen

In [4]:
parser = Sbopen()

comps = parser.competition()

comps[comps['competition_name'] == 'UEFA Euro']

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
68,55,282,Europe,UEFA Euro,male,False,True,2024,2024-07-15T15:48:50.315500,2024-07-15T15:52:24.778809,2024-07-15T15:52:24.778809,2024-07-15T15:48:50.315500
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402

In [16]:
games = parser.match(competition_id=55, season_id=282)

games[(games['home_team_name'] == 'Poland') | (games['away_team_name'] == 'Poland')]

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,competition_stage_id,competition_stage_name,stadium_id,stadium_name,stadium_country_id,stadium_country_name,referee_id,referee_name,referee_country_id,referee_country_name
29,3938637,2024-06-16,2024-06-16 16:00:00,1,2,available,available,2024-07-12 03:37:17.747730,2024-07-12 03:39:53.010211,1,...,10,Group Stage,379,Volksparkstadion,85,Germany,2445,Artur Manuel Ribeiro Soares Dias,183,Portugal
33,3938641,2024-06-21,2024-06-21 19:00:00,1,3,available,available,2024-07-12 21:09:31.780785,2024-07-12 21:10:46.438024,2,...,10,Group Stage,367,Olympiastadion Berlin,85,Germany,845,Halil Umut Meler,233,Turkey
35,3938643,2024-06-25,2024-06-25 19:00:00,1,1,available,available,2024-07-12 06:05:55.170896,2024-07-12 06:08:47.869486,3,...,10,Group Stage,373,Signal-Iduna-Park,85,Germany,261,Marco Guida,112,Italy

In [5]:
df, related, freeze, tactics = parser.event(3938637)

pitch = Pitch(line_zorder=2)
df_pass = df.loc[df['type_name'] == 'Pass'].copy()

df_pass[['play_pattern_name']]

     play_pattern_name
4        From Kick Off
6        From Kick Off
10       From Kick Off
13        Regular Play
16        Regular Play
...                ...
3382      Regular Play
3385     From Throw In
3388     From Throw In
3391     From Throw In
3394     From Throw In

[954 rows x 1 columns]

In [7]:
df['tactics_formation']

0        352
1       4231
2       None
3       None
4       None
        ...
3396    None
3397    None
3398    None
3399    None
3400    None
Name: tactics_formation, Length: 3401, dtype: object

In [12]:
from statsbombpy import sb

events = sb.events(match_id = 3938637)

events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'block_deflection', 'carry_end_location', 'clearance_aerial_won',
       'clearance_body_part', 'clearance_head', 'clearance_left_foot',
       'clearance_right_foot', 'counterpress', 'dribble_nutmeg',
       'dribble_outcome', 'dribble_overrun', 'duel_outcome', 'duel_type',
       'duration', 'foul_committed_card', 'foul_won_defensive',
       'goalkeeper_body_part', 'goalkeeper_end_location', 'goalkeeper_outcome',
       'goalkeeper_position', 'goalkeeper_technique', 'goalkeeper_type', 'id',
       'index', 'interception_outcome', 'location', 'match_id', 'minute',
       'off_camera', 'out', 'pass_aerial_won', 'pass_angle',
       'pass_assisted_shot_id', 'pass_body_part', 'pass_cross',
       'pass_cut_back', 'pass_deflected', 'pass_end_location',
       'pass_goal_assist', 'pass_height', 'pass_inswinging', 'pass_length',
       'pass_no_touch', 'pass_outcome', 'pass_outswinging', 'pass_recipient',
       'pass_recipient_id', 'pass_shot_assist', 'pass_switch',
       'pass_technique', 'pass_through_ball', 'pass_type', 'period',
       'play_pattern', 'player', 'player_id', 'position', 'possession',
       'possession_team', 'possession_team_id', 'related_events', 'second',
       'shot_aerial_won', 'shot_body_part', 'shot_deflected',
       'shot_end_location', 'shot_first_time', 'shot_freeze_frame',
       'shot_key_pass_id', 'shot_one_on_one', 'shot_outcome',
       'shot_statsbomb_xg', 'shot_technique', 'shot_type',
       'substitution_outcome', 'substitution_replacement', 'tactics', 'team',
       'team_id', 'timestamp', 'type', 'under_pressure'],
      dtype='object')